// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0J1mKLd0KyIGEtMSUrT7HOInytgQFQs',
    appId: '1:827127108310:web:0ec46dbe01e3166d00ef77',
    messagingSenderId: '827127108310',
    projectId: 'antrian-3f3d2',
    authDomain: 'antrian-3f3d2.firebaseapp.com',
    storageBucket: 'antrian-3f3d2.firebasestorage.app',
    measurementId: 'G-SWR196P9DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdGC4J4jxnVrvCBRuYgA4svwxLqjEDsDY',
    appId: '1:827127108310:android:83eff1efa35cf36100ef77',
    messagingSenderId: '827127108310',
    projectId: 'antrian-3f3d2',
    storageBucket: 'antrian-3f3d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmC3xRSRfEoABzjIyY0cOeylhr9kNNtHU',
    appId: '1:827127108310:ios:d04123c429d01b7a00ef77',
    messagingSenderId: '827127108310',
    projectId: 'antrian-3f3d2',
    storageBucket: 'antrian-3f3d2.firebasestorage.app',
    iosBundleId: 'com.antigravity.digitalqueue.digitalQueueApp',
  );
}
